- name: "Adding Locations"
  connection: local
  hosts: localhost
  gather_facts: False
  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url: "your url"
      netbox_token: "your api token"

  tasks:
    - name: Read users from CSV file
      community.general.read_csv:
        path: 'your csv file path'
      register: name_of_file
      delegate_to: localhost

    - name: Create locations
      netbox.netbox.netbox_location:
        data:
          name: "{{ device['ROOM-NO'] }}"
          site: "{{ device.SITES }}"
        state: present
      loop: "{{ output2.list }}"
      loop_control:
        loop_var: device 



